default_context:
  _pegasus_version: '2022.10'
  author_name: Maurice
  ci: github_actions
  css_framework: tailwind
  css_theme: default
  database: postgres
  deploy_platform: digital_ocean_app_platform
  description: The most amazing SaaS application the world has ever seen
  domain_name: localhost:8000
  email: maurice.schilpp.beyond@gmail.com
  enable_google_login: y
  enable_twitter_login: y
  front_end_framework: react
  project_name: SendBill
  project_slug: send_bill
  stripe_payment_mode: both
  subscription_billing_model: default
  use_2fa: y
  use_api_keys: y
  use_docker: y
  use_impersonation: y
  use_sentry: y
  use_subscriptions: y
  use_teams: y
  use_translations: y
  use_wagtail: n
